### PR TITLE
Add instruction in README for testing Cfn through SAM

### PR DESCRIPTION
**Pull request by gimki**
*Issue #, if available:*

*Description of changes:*

Adding instruction for running tests through SAM on README.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by lambrospetrou** [comment]
We don't have the SAM test in a pipeline or something but you can and should run them locally. See the instructions at https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-type-walkthrough.html#resource-type-walkthrough-test how they are used.

**Comment by gimki** [comment]
> We don't have the SAM test in a pipeline or something but you can and should run them locally. See the instructions at https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-type-walkthrough.html#resource-type-walkthrough-test how they are used.

But what is the difference between running the SAM test and running it through 

`cfn generate` -> `cfn submit -v --region us-east-1` -> create stack ?

(Apart from running one less command possibly).

**Comment by ivoanjo** [comment]
Perhaps we could instead add the link that Lambros left to the README? :)

You're angering his ghost :D

**Comment by lambrospetrou** [comment]
> Perhaps we could instead add the link that Lambros left to the README? :)
> 
> You're angering his ghost :D

All links are inside <https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-codeguru-profiler/blob/master/aws-codeguruprofiler-profilinggroup/README.md>. It's not the first time someone misses something because they are in the sub-directory README. It could be worth moving them out to the root README. Initially I treated each subdirectory as a separate project since it's standalone but maybe it was a mistake and the root README should have all the info for a newcomer.

**Pull request merged**
